import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property<[string]> displayed_tokenstream: ["T", "E", "S"];
    in-out property<[string]> previous_tokenstream: [];

    callback key_pressed(string);
    callback button_clicked(string);
    pure callback flatten_tokenstream([string]) -> string;

    keyboard_handler := FocusScope { key-pressed(event) => { root.key_pressed(event.text); accept } }
    VerticalBox {
        Text { 
            text: root.flatten_tokenstream(root.displayed_tokenstream);
        }
        GridLayout {
            Row {
                clear := Button { text: "C"; clicked => { root.button_clicked(self.text); } }
                left_bracket := Button { text: "("; clicked => { root.button_clicked(self.text); } }
                right_bracket := Button { text: ")"; clicked => { root.button_clicked(self.text); } }
                mod := Button { text: "mod"; clicked => { root.button_clicked(self.text); } }
                pi := Button { text: "π"; clicked => { root.button_clicked(self.text); } }
            }
            Row {
                seven := Button { text: "7"; clicked => { root.button_clicked(self.text); } }
                eight := Button { text: "8"; clicked => { root.button_clicked(self.text); } }
                nine := Button { text: "9"; clicked => { root.button_clicked(self.text); } }
                divide := Button { text: "÷"; clicked => { root.button_clicked(self.text); } }
                square-root := Button { text: "√"; clicked => { root.button_clicked(self.text); } }
            }
            Row {
                four := Button { text: "4"; clicked => { root.button_clicked(self.text); } }
                five := Button { text: "5"; clicked => { root.button_clicked(self.text); } }
                six := Button { text: "6"; clicked => { root.button_clicked(self.text); } }
                multiply := Button { text: "×"; clicked => { root.button_clicked(self.text); } }
                square := Button { text: "x²"; clicked => { root.button_clicked(self.text); } }
            }
            Row {
                one := Button { text: "1"; clicked => { root.button_clicked(self.text); } }
                two := Button { text: "2"; clicked => { root.button_clicked(self.text); } }
                three := Button { text: "3"; clicked => { root.button_clicked(self.text); } }
                subtract := Button { text: "-"; clicked => { root.button_clicked(self.text); } }
                power := Button { text: "xʸ"; clicked => { root.button_clicked(self.text); } }
            }
            Row {
                zero := Button { colspan: 2; text: "0"; clicked => { root.button_clicked(self.text); } }
                period := Button { col: 2; text: "."; clicked => { root.button_clicked(self.text); } }
                add := Button { text: "+"; clicked => { root.button_clicked(self.text); } }
                equal := Button { text: "="; clicked => { root.button_clicked(self.text); } }
            }
        }
    }
}
