import { VerticalBox } from "std-widgets.slint";

export global CalculatorLogic {
    callback is-empty(string) -> bool;
    callback key-pressed(string);
}

component CalculatorButton {
    in property <string> text;
    in property <string> key: text;
    min-height: 30px;
    max-height: 30px;
    min-width: 30px;
    in property <brush> background: #a3b4cf;
    Rectangle {
        background: ta.pressed ? blue : ta.has-hover ? background.darker(10%) : background;
        animate background { duration: 100ms; }
        border-radius: 4px;
        border-width: 2px;
        border-color: self.background.darker(20%);
        ta := TouchArea {
            clicked => { CalculatorLogic.key-pressed(CalculatorLogic.is-empty(root.key) ? root.text : root.key); }
        }
    }
    Text { text: root.text; }
}

export component CalculatorApp inherits Window {
    in property <string> input: "0";
    in property <string> result: "0";

    FocusScope { key-pressed(event) => { CalculatorLogic.key-pressed(event.text); accept } }
    GridLayout {
        padding: 10px;
        spacing: 5px;
        Row {
            Text { text: result; colspan: 5; }
        }
        Row {
            Text { text: input; colspan: 5; }
        }
        Row {
            CalculatorButton { text: "C"; key: "\u{7f}"; }
            CalculatorButton { text: "("; }
            CalculatorButton { text: ")"; }
            CalculatorButton { text: "mod"; key: "%"; }
            CalculatorButton { text: "π"; }
        }
        Row {
            CalculatorButton { text: "7"; }
            CalculatorButton { text: "8"; }
            CalculatorButton { text: "9"; }
            CalculatorButton { text: "÷"; key: "/"; }
            CalculatorButton { text: "√"; }
        }
        Row {
            CalculatorButton { text: "4"; }
            CalculatorButton { text: "5"; }
            CalculatorButton { text: "6"; }
            CalculatorButton { text: "×"; key: "*"; }
            CalculatorButton { text: "x²"; key: "^2"; }
        }
        Row {
            CalculatorButton { text: "1"; }
            CalculatorButton { text: "2"; }
            CalculatorButton { text: "3"; }
            CalculatorButton { text: "-"; }
            CalculatorButton { text: "xʸ"; key: "^"; }
        }
        Row {
            CalculatorButton { colspan: 2; text: "0"; }
            CalculatorButton { col: 2; text: "."; }
            CalculatorButton { text: "+"; }
            CalculatorButton { text: "="; key: "\n"; }
        }
    }
}
