import { VerticalBox } from "std-widgets.slint";

export global CalcLogic {
    callback is-empty(string) -> bool;
    callback key-pressed(string);
}

component CalcButton {
    in property <string> text;
    in property <string> key: text;
    min-height: 30px;
    max-height: 30px;
    min-width: 30px;
    in property <brush> background: #09aab0;
    Rectangle {
        background: ta.pressed ? background.darker(40%) : ta.has-hover ? background.darker(10%) : background;
        animate background { duration: 100ms; }
        border-radius: 4px;
        border-width: 2px;
        border-color: self.background.darker(20%);
        ta := TouchArea {
            clicked => { CalcLogic.key-pressed(CalcLogic.is-empty(root.key) ? root.text : root.key); }
        }
    }
    Text { text: root.text; }
}

export component MainWindow inherits Window {
    title: @tr("SCalcy");
    in property <string> input: "0";
    in property <string> result: "0";
    in property <[string]> history: [];

    FocusScope { key-pressed(event) => { CalcLogic.key-pressed(event.text); accept } }
    GridLayout {
        padding: 10px;
        spacing: 5px;
        Row { Text { text: history[4]; colspan: 5; horizontal-alignment: right; } }
        Row { Text { text: history[3]; colspan: 5; horizontal-alignment: right; } }
        Row { Text { text: history[2]; colspan: 5; horizontal-alignment: right; } }
        Row { Text { text: history[1]; colspan: 5; horizontal-alignment: right; } }
        Row { Text { text: history[0]; colspan: 5; horizontal-alignment: right; } }
        Row { Text { text: result; colspan: 5; } }
        Row { Text { text: input; colspan: 5; horizontal-alignment: right; } }
        Row {
            CalcButton { text: "C"; key: "\u{7f}"; }
            CalcButton { text: "("; }
            CalcButton { text: ")"; }
            CalcButton { text: "mod"; key: "%"; }
            CalcButton { text: "π"; }
        }
        Row {
            CalcButton { text: "7"; }
            CalcButton { text: "8"; }
            CalcButton { text: "9"; }
            CalcButton { text: "÷"; key: "/"; }
            CalcButton { text: "√"; }
        }
        Row {
            CalcButton { text: "4"; }
            CalcButton { text: "5"; }
            CalcButton { text: "6"; }
            CalcButton { text: "×"; key: "*"; }
            CalcButton { text: "x²"; key: "^2"; }
        }
        Row {
            CalcButton { text: "1"; }
            CalcButton { text: "2"; }
            CalcButton { text: "3"; }
            CalcButton { text: "-"; }
            CalcButton { text: "xʸ"; key: "^"; }
        }
        Row {
            CalcButton { colspan: 2; text: "0"; }
            CalcButton { col: 2; text: "."; }
            CalcButton { text: "+"; }
            CalcButton { text: "="; key: "\n"; }
        }
    }
}
